services:

   php:
      image: wodby/php:latest
      container_name: prog_m9_php
      volumes:
         - './:/var/www/html'

   nginx:
      image: nginx:latest
      container_name: prog_m9_nginx
      ports:
         - 81:80
      links:
         - php
      volumes:
         - './:/var/www/html'
         - './docker:/etc/nginx/conf.d'
      depends_on:
         - php
         - mariadb

   mariadb:
      image: mariadb:latest
      container_name: prog_m9_mariadb
      volumes:
         - './:/var/www/html'
      environment:
         MYSQL_DATABASE: '${DB_NAME}'
         MYSQL_USER: '${DB_USERNAME}'
         MYSQL_PASSWORD: '${DB_PASSWORD}'
         MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      ports: 
         - 3356:3306

   phpmyadmin:
      image: phpmyadmin:latest
      container_name: sd3_m9_phpmyadmin
      ports:
         - 8005:80
      depends_on:
         - mariadb
      environment:
         PMA_HOST: mariadb
         PMA_USER: '${DB_USERNAME}'
         PMA_PASSWORD: '${DB_PASSWORD}'